### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by JacobDevelopment** [JacobDevelopment/Tickster#7]
- [X] Change to ShardManager instead of JDABuilder. (Completed: f2bb163271aa98ca3019174ef3e9f3ca7c93e882)
- [X] Add Invite Caching. (Completed: 218296352b81949d428b6379d59a9482a4f60613)
- [ ] Finish TicketCommand  (In progress: 5fed8e96326cd4c8a1f6328cb6d810852fb60573)
- [X] Condense CommandError back into CommandContext, redundant. (Completed: f4365f0e3f65feb661d0b31f01a148e13aaa4c77)
- [X] Make an enum to create buttons easier (Button.of(ButtonStyle.PRIMARY) blah blah is annoying). (Completed: 429964ce71979b1cec8510fbd213241e0dfcc31c)
- [ ] Delete/Think about deleting transcript option. Doesn't follow privacy standards (GDPR/Discord/etc.)
